config/routes.rb
Rails.application.routes.draw do
  resources :coffee_statuses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'coffee_statuses/new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee_status.rb
class CoffeeStatus < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coffee_statuses_controller.rb
class CoffeeStatusesController < ApplicationController
  before_action :set_coffee_status, only: [:show, :edit, :update, :destroy]
  require 'pry'
  # GET /coffee_statuses
  # GET /coffee_statuses.json
  def index
    @coffee_statuses = CoffeeStatus.all.order("last_updated DESC")
  end

  # GET /coffee_statuses/1
  # GET /coffee_statuses/1.json
  def show
  	@coffee_status = CoffeeStatus.find(params[:id])
  end

  # GET /coffee_statuses/new
  def new
    @coffee_status = CoffeeStatus.new
  end

  # GET /coffee_statuses/1/edit
  def edit
  end

  # POST /coffee_statuses
  # POST /coffee_statuses.json
  def create
    @coffee_status = CoffeeStatus.new(coffee_status_params)
    @coffee_status[:last_updated] = Time.now()
    respond_to do |format|
      if @coffee_status.save
        format.html { redirect_to coffee_statuses_path, notice: 'Coffee status was successfully created.' }
        format.json { render :show, status: :created, location: @coffee_status }
      else
        format.html { render :new }
        format.json { render json: @coffee_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_statuses/1
  # PATCH/PUT /coffee_statuses/1.json
  def update
    respond_to do |format|
    	binding.pry
    	@coffee_status[:last_updated] = Time.now()
      if @coffee_status.update(coffee_status_params)
        format.html { redirect_to coffee_statuses_path, notice: 'Coffee status was successfully updated.' }
        format.json { render :show, status: :ok, location: @coffee_status }
      else
        format.html { render :edit }
        format.json { render json: @coffee_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_statuses/1
  # DELETE /coffee_statuses/1.json
  def destroy
    @coffee_status.destroy
    respond_to do |format|
      format.html { redirect_to coffee_statuses_url, notice: 'Coffee status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_status
      @coffee_status = CoffeeStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffee_status_params
      params.require(:coffee_status).permit(:available, :user_updated_last, :last_updated)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_statuses_helper.rb
module CoffeeStatusesHelper
end

app/views/coffee_statuses/_form.html.erb
<%= form_with(model: coffee_status, local: true) do |form| %>
  <% if coffee_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffee_status.errors.count, "error") %> prohibited this coffee_status from being saved:</h2>

      <ul>
      <% coffee_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available, id: :coffee_status_available %>
  </div>

  <div class="field">
    <%= form.label :user_updated_last %>
    <%= form.text_field :user_updated_last, id: :coffee_status_user_updated_last %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coffee_statuses/edit.html.erb
<h1>Editing Coffee Status</h1>

<%= render 'form', coffee_status: @coffee_status %>

<%= link_to 'Show', @coffee_status %> |
<%= link_to 'Back', coffee_statuses_path %>

app/views/coffee_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffee Statuses</h1>

<table>
  <tbody>
    <% @coffee_statuses.each do |coffee_status| %>
      <tr>
      	<% if coffee_status.available === true %>
        	<td><%= image_tag("download.png", height: '32', width: '32') %></td>
        	<td><%= coffee_status.available %></td>
        	<td><%= coffee_status.last_updated %></td>
        <% elsif coffee_status.available === false %>
        	<td><%= image_tag("angry.png", height: '32', width: '32') %></td>
        	<td><%= coffee_status.available %></td>
        	<td><%= coffee_status.last_updated %></td>
        <% end %>
        <td><%= coffee_status.user_updated_last %></td>
        <td><%= link_to 'Show', coffee_status %></td>
        <td><%= link_to 'Edit', edit_coffee_status_path(coffee_status) %></td>
        <td><%= link_to 'Destroy', coffee_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffee Status', new_coffee_status_path %>

app/views/coffee_statuses/new.html.erb
<h1>New Coffee Status</h1>

<%= render 'form', coffee_status: @coffee_status %>

<%= link_to 'Back', coffee_statuses_path %>

app/views/coffee_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Available:</strong>
  <%= @coffee_status.available %>
</p>

<p>
  <strong>User updated last:</strong>
  <%= @coffee_status.user_updated_last %>
</p>

<%= link_to 'Edit', edit_coffee_status_path(@coffee_status) %> |
<%= link_to 'Back', coffee_statuses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>